[package]
name = "poem"
version = "0.1.0"
authors = ["piaoger"]
edition = "2018"

[dependencies]
tokio = { version = "1", features = ["full"] }
poem = "1.2"
serde = { version = "1.0", features = ["derive"] }